/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AMCM1RZZ7Cr
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { LoginWithGoogleButton } from "./login-with-google-button"
import { getServerAuthSession } from "~/server/auth"
import { Button } from "./ui/button";
import Link from "next/link";

export async function HomePage() {
  const session = await getServerAuthSession()
  const showLogin = !session;

  return (
    <>
      <header className="flex h-20 w-full items-center px-4 md:px-6">
        <div className="ml-auto">
          {showLogin && <LoginWithGoogleButton size="lg" variant="default" />}
        </div>
      </header>
      <main className="container mx-auto px-4 md:px-6">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="space-y-3">
            <h1 className="text-4xl font-bold tracking-tighter text-center sm:text-5xl md:text-6xl">
              Welcome to MeroFYP
            </h1>
            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 text-center">
              Your one-stop solution to final year projects. Get your fyp projects done by industry experts without deep pockets 😉
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mt-8">
            <Card>
              <CardHeader>
                <h2 className="text-2xl font-semibold">Affordable Subscription Model</h2>
              </CardHeader>
              <CardContent>
                <p className="text-gray-500 dark:text-gray-400">
                  Pay for the duration you want. Get your FYP done in no time.
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <h2 className="text-2xl font-semibold">Collaborative Environment</h2>
              </CardHeader>
              <CardContent>
                <p className="text-gray-500 dark:text-gray-400">
                  Provide feedback and ask questions directly to the developer
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <h2 className="text-2xl font-semibold">Secure and Reliable</h2>
              </CardHeader>
              <CardContent>
                <p className="text-gray-500 dark:text-gray-400">
                  Your data is safe with us. Your supervisors will think you did your FYP 😜
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <h2 className="text-2xl font-semibold">Excillent Drag-and-Drop builder</h2>
              </CardHeader>
              <CardContent className="flex flex-col space-y-4">
                <p className="text-gray-500 dark:text-gray-400">
                  Build unlimited full-stack websites just with drag and drop and publish them for as long as you are subscribed.
                  Don't worry, you can still use the builder without subscription.
                </p>
                <Link href="/builder">
                  <Button className="w-full">
                    Try now for free
                  </Button>
                </Link>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
    </>
  )
}
