/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/j6tSza98reY
 */
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function LoginForm() {
  return (
    <div className="mx-auto max-w-sm space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Login</h1>
        <p className="text-gray-500 dark:text-gray-400">Login with your Google organization account</p>
      </div>
      <div className="space-y-4">
        <Link href='/login/journey'>
          <Button className="w-full" variant="outline" >
            <ChromeIcon className="w-4 h-4 mr-2" />
            Login with Google
          </Button>
        </Link>
      </div>
    </div>
  )
}


function ChromeIcon(props: { className: string }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  )
}
