/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9FK4gNCtAGn
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Input } from "./ui/input";
import { Label } from "./ui/label";

type FypCardContent = {
  head: {
    key: string,
    description: string,
  },
  form: {
    header: {
      title: string,
    },
    content?: {
      key: string,
      placeholder: string,
      required?: boolean,
    }[],
    link?: {
      href: string,
      text: string,
    },
  }[],
};

const cardContent: FypCardContent = {
  head: {
    key: "User Registration",
    description: "Please enter your details to create an account",
  },
  form: [
    {
      header: {
        title: "Step 1: Personal Information",
      },
      content: [
        {
          key: "First Name",
          placeholder: "John",
          required: true,
        },
        {
          key: "Last Name",
          placeholder: "Doe",
          required: true,
        },
      ],
    },
    {
      header: {
        title: "Step 2: College Selection",
      },
      content: [
        {
          key: "College",
          placeholder: "Harvard University",
        }
      ],
    },
    {
      header: {
        title: "Step 3: Batch and Course Selection",
      },
      content: [
        {
          key: "Batch",
          placeholder: "2022",
          required: true,
        },
        {
          key: "Course",
          placeholder: "Computer Science",
          required: true,
        },
      ],
      link: {
        href: "/subscription/",
        text: "Register",
      },
    },
  ],
};

export function LoginJourneyForm() {
  return (
    <div className="mx-auto max-w-lg space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">{cardContent.head.key}</h1>
        <p className="text-gray-500 dark:text-gray-400">{cardContent.head.description}</p>
      </div>
      {
        cardContent.form.map(
          ({ header, content, link }) => (
            <div className="flex flex-col space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle>{header?.title ?? ""}</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  {
                    content?.length === 1 ? <div className="space-y-2">
                      <Label htmlFor={content[0]!.key}>
                        {content[0]!.key}
                      </Label>
                      <Input id={content[0]!.key} placeholder={content[0]!.placeholder} required={content[0]!.required ?? false} />
                    </div> :
                      <div className="grid grid-cols-2 gap-4">
                        {
                          content?.map(({ key, placeholder, required = false }) => {
                            return <div className="space-y-2" key={key}>
                              <Label htmlFor={key}>{key}</Label>
                              <Input id={key} placeholder={placeholder} required={required} />
                            </div>
                          })
                        }
                      </div>
                  }
                </CardContent>
              </Card>
              {
                link &&
                <Link href={`/${link.href}/`} className="my-8">
                  <Button className="w-full" type="submit">
                    {link.text}
                  </Button>
                </Link>
              }
            </div>
          ),
        )
      }
    </div>
  )
}
