"use client"

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DHCn4V5PQof
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import Link from "next/link"
import { type Session } from "next-auth"
import { Button } from "./ui/button"
import { useRouter } from "next/navigation"
import { signOut } from "next-auth/react"
import { useState } from "react"

export function ProfileAvatar({ user: { user: { image, name, email } } }: { user: Session }) {
  const router = useRouter();
  const [open, setOpen] = useState(false);

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Avatar className="h-9 w-9">
          <AvatarImage alt="User avatar" src={image ?? ""} />
          <AvatarFallback className="capitalize">{name?.at(0)}</AvatarFallback>
        </Avatar>
      </PopoverTrigger>
      <PopoverContent className="w-80">
        <Card className="shadow-none bg-transparent border-0">
          <CardHeader className="border-b">
            <CardTitle>User Profile</CardTitle>
            <CardDescription>Manage your account</CardDescription>
          </CardHeader>
          <CardContent className="p-6">
            <div className="space-y-4">
              <div className="flex items-center space-x-2">
                <Avatar className="h-12 w-12">
                  <AvatarImage alt="User avatar" src={image ?? ""} />
                  <AvatarFallback className="capitalize">{name?.at(0)}</AvatarFallback>
                </Avatar>
                <div className="space-y-1">
                  <h4 className="text-lg font-semibold">{name}</h4>
                  <p className="text-sm text-gray-500 dark:text-gray-400">{email}</p>
                </div>
              </div>
              <Link className="underline" href="#">
                Account Settings
              </Link>
              <Button className="w-full" onClick={async () => {
                await signOut({ redirect: false });
                setOpen(false);
                router.replace("/");
                router.refresh();
              }} variant="outline">
                Logout
              </Button>
            </div>
          </CardContent>
        </Card>
      </PopoverContent>
    </Popover>
  )
}
